media_alias_display.settings:
  type: config_object
  label: 'Media Alias Display settings'
  constraints:
    FullyValidatable: ~
  mapping:
    kill_switch:
      type: boolean
      label: 'Disable media_alias_display completely'
    media_bundles:
      type: sequence
      label: 'Media Bundles allowed to use media_alias_download'
      sequence:
        type: machine_name
        label: 'Media Bundle ID'
        constraints:
          NotBlank:
            allowNull: false
